apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "modelfs.fullname" . }}
  namespace: {{ include "modelfs.namespace" . }}
  labels:
    {{- include "modelfs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "modelfs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "modelfs.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "modelfs.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: manager
        command:
        - /app/manager
        args:
        {{- if .Values.leaderElection.enabled }}
        - --leader-elect
        {{- if .Values.leaderElection.resourceName }}
        - --leader-election-resource-name={{ .Values.leaderElection.resourceName }}
        {{- end }}
        {{- end }}
        image: {{ include "modelfs.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}

