{{- if and .Values.ui.enabled .Values.ui.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "modelfs.fullname" . }}-ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "modelfs.fullname" . }}-ui
subjects:
  - kind: ServiceAccount
    name: {{ default (printf "%s-ui" (include "modelfs.name" .)) .Values.ui.serviceAccount.name }}
    namespace: {{ .Values.namespace.name }}
{{- end -}}

