{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "modelfs.fullname" . }}-ui
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    app: {{ include "modelfs.fullname" . }}-ui
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: {{ .Values.ui.service.port }}
      protocol: TCP
      name: http
{{- end -}}

