{{- if and .Values.ui.enabled .Values.ui.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-ui" (include "modelfs.name" .)) .Values.ui.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
{{- end -}}

