apiVersion: model.samzong.dev/v1
kind: ModelSync
metadata:
  name: sample-sync
spec:
  modelRef: sample-model
  version: v1.0.0  # Required: must be one of the versions defined in Model.spec.versionConfigs
  schedule: "@hourly"
  retentionCount: 3
