apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/model.samzong.dev_models.yaml
  - bases/model.samzong.dev_modelsources.yaml
  - bases/dataset.baizeai.io_datasets.yaml
